.TH "mm5d-getsnapshots" "1" "0.3" "Pozsár Zsolt" "MM5D"
.SH "NAME"
.LP 
mm5d-getsnapshots - create diagrams from log for web interface
.SH "SYNTAX"
.LP
\fBmm5d-getsnapshots\fP
.SH "DESCRIPTION"
.LP 
This is a part of MM5D growing house controlling and remote monitoring
system. This script gets snapshot from IP cameras. Do not run manually,
a cgi program runs it.
.SH FILES
.LP
.TP
\fI/etc/mm5d/mm5d.ini\fR or \fI/usr/local/etc/mm5d/mm5d.ini\fR
configuration file
.TP
\fIpics/ants.jpg\fR in html directory of webserver
noisy screenshot
.TP
\fIpics/camera1.jpg\fR in html directory of webserver
output file
.TP
\fIpics/camera2.jpg\fR in html directory of webserver
output file
.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B 1
Configuration file is missing.
.SH "HOMEPAGE"
\fIhttp://www.szerafingomba.hu/softwares/\fR
.SH "SEE ALSO"
.PD 0
.LP
\fBmatrixdisplay.py\fP(1)
\fBmm5d-creatediagrams\fP(1)
\fBmm5d-editenvirconf\fP(1)
\fBmm5d-editmainconf\fP(1)
\fBmm5d-hwtest.py\fP(1)
\fBmm5d-maintainlog\fP(1)
\fBmm5d-override\fP(1)
\fBmm5d.py\fP(1)
\fBmm5d-startdaemon\fP(1)
\fBmm5d-statusofdaemon\fP(1)
\fBmm5d-stopdaemon\fP(1)
\fBmm5d-updatestartpage\fP(1)
\fBmm5d-viewlog\fP(1)
\fBmm5d-webpage\fP(1)
and \fI/usr/share/doc/mm5d/\fP or equivalent on your system.
.SH "AUTHOR"
Pozsár Zsolt \fIpozsar.zsolt@szerafingomba.hu\fR
