.TH "mm5d-override" "1" "0.3" "Pozsár Zsolt" "MM5D"
.SH "NAME"
.LP 
mm5d-override - override output state
.SH "SYNTAX"
.LP
\fBmm5d-override\fP -f|--full-screen
.br
\fBmm5d-override\fP heater|light|ventilator|humidifier neutral|on|off
.SH "DESCRIPTION"
.LP 
This is a part of MM5D growing house controlling and remote monitoring
system. You can get status and switch on or off outputs, override control
program.
.SH OPTIONS
.TP
.B \fIheater\fP, \fIlight\fP, \fIventilator\fP, \fIhumidifier\fP
Select output.
.TP
.B \fIneutral\fP, \fIon\fP, \fIoff\fP
Select state. Neutral is not changes state of output.
.TP
.BR \-f ", " \-\-full-screen
Start full screen setting program.
.SH FILES
.LP
.TP
\fI/etc/mm5d/mm5d.ini\fR or \fI/usr/local/etc/mm5d/mm5d.ini\fR
configuration file
.TP
\fIout1\fR, \fIout2\fR, \fIout3\fR and \fIout4\fR in directory of changing files
output state files
.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B 1
Configuration file is missing.
.TP
.B 2
No or bad command line parameters.
.SH "HOMEPAGE"
\fIhttp://www.szerafingomba.hu/softwares/\fR
.SH "SEE ALSO"
.PD 0
.LP
\fBmatrixdisplay.py\fP(1)
\fBmm5d-creatediagrams\fP(1)
\fBmm5d-editenvirconf\fP(1)
\fBmm5d-editmainconf\fP(1)
\fBmm5d-getsnapshots\fP(1)
\fBmm5d-hwtest.py\fP(1)
\fBmm5d-maintainlog\fP(1)
\fBmm5d.py\fP(1)
\fBmm5d-startdaemon\fP(1)
\fBmm5d-statusofdaemon\fP(1)
\fBmm5d-stopdaemon\fP(1)
\fBmm5d-updatestartpage\fP(1)
\fBmm5d-viewlog\fP(1)
\fBmm5d-webpage\fP(1)
and \fI/usr/share/doc/mm5d/\fP or equivalent on your system.
.SH "AUTHOR"
Pozsár Zsolt \fIpozsar.zsolt@szerafingomba.hu\fR
