.TH "mm5d-editenvirconf" "1" "0.3" "Pozsár Zsolt" "MM5D"
.SH "NAME"
.LP 
mm5d-editenvirconf - configuration editor
.SH "SYNTAX"
.LP
\fBmm5d-editenvirconf\fP
.SH "DESCRIPTION"
.LP 
This is a part of MM5D growing house controlling and remote monitoring
system. Run this program if you want to edit configuration file of growing
environment characteristic.
.SH FILES
.LP
.TP
\fI/etc/mm5d/envir.ini\fR or \fI/usr/local/etc/mm5d/envir.ini\fR
configuration file
.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B 1
Configuration file is missing.
.SH "HOMEPAGE"
\fIhttp://www.szerafingomba.hu/softwares/\fR
.SH "SEE ALSO"
.PD 0
.LP
\fBmatrixdisplay.py\fP(1)
\fBmm5d-creatediagrams\fP(1)
\fBmm5d-editmainconf\fP(1)
\fBmm5d-getsnapshots\fP(1)
\fBmm5d-hwtest.py\fP(1)
\fBmm5d-maintainlog\fP(1)
\fBmm5d-override\fP(1)
\fBmm5d.py\fP(1)
\fBmm5d-startdaemon\fP(1)
\fBmm5d-statusofdaemon\fP(1)
\fBmm5d-stopdaemon\fP(1)
\fBmm5d-updatestartpage\fP(1)
\fBmm5d-viewlog\fP(1)
\fBmm5d-webpage\fP(1)
and \fI/usr/share/doc/mm5d/\fP or equivalent on your system.
.SH "AUTHOR"
Pozsár Zsolt \fIpozsar.zsolt@szerafingomba.hu\fR
