#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.6 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2023 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | prepare                                                                    |
# | Prepare OS                                                                 |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

line()
{
  for ((i=0; i<${#SWCR}; i++))
  do
    echo -n "-"
  done
  echo ""
}

# constants
SWN1="MM5D"
SWN2="mm5d"
SWCR=`cat documents/copyright`
SWV=`cat documents/VERSION`

# prepare
echo -e "\n$SWN1 v$SWV prepare OS"
echo "$SWCR"
line
sleep 1
echo "Installing required components..."
sudo apt-get install apache2 \
                     build-essential \
                     git \
                     gnuplot \
                     libfreetype6-dev \
                     libjpeg-dev \
                     libswitch-perl \
                     python3-daemon \
                     python3-dev \
                     python3-openssl \
                     python3-pip \
                     python3-requests \
                     python3-rpi.gpio \
                     python-configparser \
                     libconfig-tiny-perl \
                     wget
echo -e "\nCloning 3rd party softwares from Github..."
mkdir --parents $HOME/download
cd $HOME/download
# clone sensor software
git clone https://github.com/adafruit/Adafruit_Python_DHT.git
cd Adafruit_Python_DHT
sudo python3 setup.py install
cd ..
# clone display software
git clone http://github.com/rm-hull/luma.led_matrix.git
cd luma.led_matrix
sudo python3 setup.py install
cd ..
echo -e "\nSetting Apache2..."
sudo ln --force --symbolic /etc/apache2/mods-available/cgid.load /etc/apache2/mods-enabled/
sudo ln --force --symbolic /etc/apache2/mods-available/cgid.conf /etc/apache2/mods-enabled/
sudo ln --force --symbolic /etc/apache2/conf-available/serve-cgi-bin.conf /etc/apache2/conf-enabled/
sudo /etc/init.d/apache2 restart
echo -e "\nDone."
