#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
# | prepare                                                                    |
# | Prepare OS                                                                 |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

SWN1="MM5D"
SWN2="mm5d"
SWV=`cat documents/VERSION`

clear
echo "--------------------------------------------------------------------------------"
echo "$SWN1 $SWV prepare OS"
echo "Copyright (C) 2019 Pozsar Zsolt <pozsar.zsolt@szerafingomba.hu>"
echo "--------------------------------------------------------------------------------"
echo "Installing required components..."
sudo apt-get install apache2 \
                     build-essential \
                     dialog \
                     git \
                     libswitch-perl \
                     python-daemon \
                     python-dev \
                     python-openssl \
                     python-rpi.gpio
mkdir --parents $HOME/download
cd $HOME/download
git clone https://github.com/adafruit/Adafruit_Python_DHT.git
cd Adafruit_Python_DHT
sudo python setup.py install
cd ..



echo -e "\nCreating a new user..."
sudo adduser $SWN2
sudo mkdir --parents /home/$SWN2/programs
sudo chown -R $SWN2:$SWN2 /home/$SWN2/programs
sudo mkdir --parents /home/$SWN2/cfg_example
sudo chown -R $SWN2:$SWN2 /home/$SWN2/cfg_example
sudo echo "$SWN2 ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/010_$SWN2-nopasswd
echo -e "\nSetting Apache2..."
sudo ln --symbolic /etc/apache2/mods-available/cgid.load /etc/apache2/mods-enabled/
sudo ln --symbolic /etc/apache2/mods-available/cgid.conf /etc/apache2/mods-enabled/
sudo ln --symbolic /etc/apache2/conf-available/serve-cgi-bin.conf /etc/apache2/conf-enabled/
sudo /etc/init.d/apache2 restart
echo -e "\nDone."
