# +----------------------------------------------------------------------------+
# | MM5D v0.3 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_de.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM5D Steuerung und Kontrollsystem
msg02=Benutzerdaten
msg03=Benutzer
msg04=Site Name
msg05=Wachsendes Haus
msg06=Name
msg07=Eingang
msg08=Ausgang
msg09=Fehler
msg10=Gehe zu Daten
msg11=Site-Adresse
msg12=Datum
msg13=Zeit
msg14=T
msg15=RH
msg16=Ein
msg17=Aus
msg18=Fehler
msg19=Aktualisiert
msg20=Letzter Zustand
msg21=Tagebuch
msg22=Kameras
msg23=Wenn Sie das vollständige Tagebuch anzeigen möchten, melden Sie sich mit SSH am Gerät an und verwenden Sie <i>mm5d-viewlog</i>!
msg24=Ausgänge überschreiben
msg25=neutral
msg26=eingeschaltet
msg27=ausgeschaltet
msg28=Um Override zu setzen, loggen Sie sich bitte über SSH in das Gerät ein und verwenden Sie den Befehl <i>mm5d-override</i>!
msg29=Um die Umgebungseigenschaften einzustellen, melden Sie sich bitte über SSH an der Unit an und verwenden Sie den Befehl <i>mm5d-editenvirconf</i>!
