# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
# | mm5d_hu.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM5D vezérlő és ellenőrző rendszer
msg02=Felhasználói adatok
msg03=Felhasználó
msg04=Telephely neve
msg05=Termesztőház
msg06=Elnevezések
msg07=Bemenet
msg08=Kimenet
msg09=Hibajelző
msg10=Tovább az adatokhoz
msg11=Telephely címe
msg12=Dátum
msg13=Idő
msg14=T
msg15=RH
msg16=Be
msg17=Ki
msg18=Hiba
msg19=Frissít
msg20=Utolsó állapot
msg21=Napló
msg22=Utolsó húsz bejegyzés
msg23=Ha szeretné látni a teljes naplót, jelentkezzen be az egységbe SSH-val és használja a <i>mm3d-viewlog</i> parancsot!
