# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_pl.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01 = System sterowania i kontroli MM5D
msg02 = Dane użytkownika
Msg03 = Użytkownik
msg04 = Nazwa witryny
msg05 = Dorastający dom
Msg06 = Nazwy
Msg07 = Wejście
msg08 = Wyjście
Msg09 = Docelowa błędu
msg10 = Przejdź do danych
msg11 = Adres strony
Msg12 = Data
msg13 = Czas
Msg14 = T
Msg15 = RH
Msg16 = Włącz
Msg17 = Wyłącz
msg18 = Błąd
Msg19 = Aktualizacja
msg20 = Ostatni stan
msg21 = Dziennik
msg22 = Ostatnie dwadzieścia wpisów
msg23 = Jeśli chcesz zobaczyć pełny dziennik, zaloguj się do urządzenia za pomocą SSH i użyj <i> mm3d-viewlog </i>!

