# +----------------------------------------------------------------------------+
# | MM5D v0.5 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_pl.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=System sterowania i kontroli MM5D
msg02=Dane użytkownika
msg03=Użytkownik
msg04=Nazwa witryny
msg05=Dorastający dom
msg06=Nazwy
msg07=Wejście
msg08=Wyjście
msg09=Docelowa błędu
msg10=Przejdź do danych
msg11=Adres strony
msg12=Data
msg13=Czas
msg14=T
msg15=RH
msg16=Włącz
msg17=Wyłącz
msg18=Błąd
msg19=Aktualizacja
msg20=Ostatni stan
msg21=Dziennik
msg22=Kamery
msg23=Jeśli chcesz zobaczyć pełny dziennik, zaloguj się do urządzenia za pomocą SSH i użyj <i>mm5d-viewlog</i>!
msg24=Nadrzędne wyjścia
msg25=neutralny
msg26=włączony
msg27=wyłączony
msg28=Aby ustawić nadpisanie, zaloguj się do urządzenia przez SSH i użyj polecenia <i>mm5d-override</i>!
msg29=Aby ustawić charakterystykę środowiska, zaloguj się do jednostki przez SSH i użyj polecenia <i>mm5d-editenvirconf</i>!
msg30=Charakterystyka środowiskowa
msg31=Rosnące strzępki
msg32=Rosnący grzyb
msg33=grzałka
msg34=nawilżacz
msg35=wentylator
msg36=lampa
msg37=wł.
msg38=wył.
msg39=minimum
msg40=maksymalna
msg41=wyłącz włączenie zasilania
msg42=czas
