# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_hr.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM5D kontrolni sustav
msg02=Korisnički podaci
msg03=Korisnik
msg04=Naziv web-mjesta
msg05=Kuća koja raste
msg06=Imena
msg07=Ulaz
msg08=izlaz
msg09=Greška
msg10=Idi na podatke
msg11=Adresa web-lokacije
msg12=Datum
msg13=Vrijeme
msg14=T
msg15=RH
msg16=Uključeno
msg17=Isključeno
msg18=Greška
msg19=Ažurirano
msg20=Zadnje stanje
msg21=Prijava
msg22=Posljednjih dvadeset zapisa
msg23=Ako želite vidjeti potpuni dnevnik, prijavite se na jedinicu sa SSH-om i koristite <i> mm3d-viewlog </i>!
