# +----------------------------------------------------------------------------+
# | MM5D v0.5 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_cs.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=Řídicí systém MM5D
msg02=Uživatelská data
msg03=Uživatel
msg04=Název webu
msg05=Rostoucí dům
msg06=Jména
msg07=Vstup
msg08=Výstup
msg09=Chyba
msg10=Přejít na data
msg11=Adresa webu
msg12=Datum
msg13=Čas
msg14=T
msg15=RH
msg16=Zapnuto
msg17=Vypnuto
msg18=Chyba
msg19=Aktualizováno
msg20=Poslední stav
msg21=Diář
msg22=Kamery
msg23=Pokud chcete zobrazit celý diář, přihlaste se k jednotce pomocí SSH a použijte <i>mm5d-viewlog</i>!
msg24=Přepsat výstupy
msg25=neutrální
msg26=zapnutý
msg27=vypnut
msg28=Chcete-li nastavit přepsání, přihlaste se do jednotky přes SSH a použijte příkaz <i>mm5d-override</i>!
msg29=Pro nastavení charakteristiky prostředí se prosím přihlaste do jednotky přes SSH a použijte příkaz <i>mm5d-editenvirconf</i>!
msg30=Charakteristika prostředí
msg31=Rostoucí hyfy
msg32=Pěstování hub
msg33=ohřívač
msg34=zvlhčovač
msg35=ventilátor
msg36=lampa
msg37=on
msg38=vypnuto
msg39=minimum
msg40=maximum
msg41=zakázat zapnutí
msg42=načasováno
