# +----------------------------------------------------------------------------+
# | MM5D v0.5 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_sl.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM5D kontrolni sistem
msg02=Uporabniški podatki
msg03=Uporabnik
msg04=Ime mesta
msg05=Hiša, ki raste
msg06=Imena
msg07=Vnosa
msg08=Izhod
msg09=Napaka
msg10=Pojdi na podatke
msg11=Naslov mesta
msg12=Datum
msg13=čas
msg14=T
msg15=RH
msg16=Vklop
msg17=Izklop
msg18=Napaka
msg19=Posodobljeno
msg20=Zadnje stanje
msg21=Dnevnik
msg22=Kamere
msg23=Če želite videti celoten dnevnik, se prijavite v enoto s SSH in uporabite <i>mm5d-viewlog</i>!
msg24=Preglasite izhode
msg25=nevtralen
msg26=vklopljen
msg27=izklopljen
msg28=Če želite nastaviti preglasitev, se prijavite v enoto prek SSH in uporabite ukaz <i>mm5d-override</i>!
msg29=Za nastavitev značilnosti okolja se prijavite v enoto prek SSH in uporabite ukaz <i>mm5d-editenvirconf</i>!
msg30= Značilnost okolja
msg31=Rasteče hife
msg32=Rasteče gobe
msg33=grelec
msg34=vlažilec zraka
msg35=ventilator
msg36=svetilka
msg37=vklopljeno
msg38=izklopljeno
msg39=najmanj
msg40=največ
msg41=onemogoči vklop
msg42=časovno
