# +----------------------------------------------------------------------------+
# | MM5D v0.6 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2023 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | mm5d_fr.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=Système de contrôle MM5D
msg02=Données utilisateur
msg03=Utilisateur
msg04=Nom du site
msg05=Maison en croissance
msg06=Noms
msg07=Entrée
msg08=Sortie
msg09=Erreur
msg10=Aller aux données
msg11=Adresse du site
msg12=Date
msg13=Temps
msg14=T
msg15=RH
msg16=Marche
msg17=Arrêt
msg18=Erreur
msg19=Mise à jour
msg20=Dernier état
msg21=Journal
msg22=Caméras
msg23=Si vous voulez voir le journal complet, connectez-vous à l'unité avec SSH et utilisez <i>mm5d-viewlog</i>!
msg24=Ignorer les sorties
msg25=neutre
msg26=allumé
msg27=éteint
msg28=Pour définir la dérogation, veuillez vous connecter à l'unité via SSH et utiliser la commande <i>mm5d-override</i>!
msg29=Pour définir les caractéristiques de l'environnement, veuillez vous connecter à l'unité via SSH et utiliser la commande <i>mm5d-editenvirconf</i>!
msg30=Caractéristique d'environnement
msg31=Croissance des hyphes
msg32=Culture de champignons
msg33=chauffage
msg34=humidificateur
msg35=ventilateur
msg36=lampe
msg37=on
msg38=désactivé
msg39=minimum
msg40=maximale
msg41=désactiver la mise sous tension
msg42=temporisé
msg43=Mode
msg44=Statut

