# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
# | mm5d_fr.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=Système de contrôle MM5D
msg02=Données utilisateur
msg03=Utilisateur
msg04=Nom du site
msg05=Maison en croissance
msg06=Noms
msg07=Entrée
msg08=Sortie
msg09=Erreur
msg10=Aller aux données
msg11=Adresse du site
msg12=Date
msg13=Temps
msg14=T
msg15=RH
msg16=Marche
msg17=Arrêt
msg18=Erreur
msg19=Mise à jour
msg20=Dernier état
msg21=Journal
msg22=Les vingt dernières entrées
msg23=Si vous voulez voir le journal complet, connectez-vous à l'unité avec SSH et utilisez <i> mm3d-viewlog </ i>!

