# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
# | mm5d_sl.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01 = MM5D kontrolni sistem
msg02 = Uporabniški podatki
msg03 = Uporabnik
msg04 = Ime mesta
msg05 = Hiša, ki raste
Msg06 = Imena
Msg07 = Vnosa
msg08 = Izhod
Msg09 = Napaka
msg10 = Pojdi na podatke
msg11 = Naslov mesta
Msg12 = Datum
msg13 = čas
Msg14 = T
Msg15 = RH
Msg16 = Vklop
Msg17 = Izklop
msg18 = Napaka
Msg19 = Posodobljeno
msg20 = Zadnje stanje
Msg21 = Dnevnik
msg22 = Zadnjih dvajset vnosov
msg23 = Če želite videti celoten dnevnik, se prijavite v enoto s SSH in uporabite <i> mm3d-viewlog </i>!

