# +----------------------------------------------------------------------------+
# | MM5D v0.2 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2020 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_ro.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM5D sistem de control
msg02=Date utilizator
msg03=Utilizator
msg04=Numele site-ului
msg05=Cresterea casei
msg06=Nume
msg07=Intrare
msg08=ieșire
msg09=Eroare
msg10=Du-te la date
msg11=Adresa site-ului
msg12=Data
msg13=Timp
msg14=T
msg15=RH
msg16=Pornit
msg17=Oprit
msg18=Eroare
msg19=Actualizat
msg20=Ultima stare
msg21=Jurnal
msg22=Camere
msg23=Dacă doriți să vedeți jurnalul complet, conectați-vă la unitate cu SSH și folosiți <i> mm3d-viewlog </ i>!

