# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
# | mm5d_de.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM5D Steuerung und Kontrollsystem
msg02=Benutzerdaten
msg03=Benutzer
msg04=Site Name
msg05=Wachsendes Haus
msg06=Name
msg07=Eingang
msg08=Ausgang
msg09=Fehler
msg10=Gehe zu Daten
msg11=Site-Adresse
msg12=Datum
msg13=Zeit
msg14=T
msg15=RH
msg16=Ein
msg17=Aus
msg18=Fehler
msg19=Aktualisiert
msg20=Letzter Zustand
msg21=Tagebuch
msg22=Die letzten zwanzig Einträge
msg23=Wenn Sie das vollständige Tagebuch anzeigen möchten, melden Sie sich mit SSH am Gerät an und verwenden Sie <i> mm3d-viewlog </ i>!
