# +----------------------------------------------------------------------------+
# | MM5D v0.3 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2021 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_cs.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=Řídicí systém MM5D
msg02=Uživatelská data
msg03=Uživatel
msg04=Název webu
msg05=Rostoucí dům
msg06=Jména
msg07=Vstup
msg08=Výstup
msg09=Chyba
msg10=Přejít na data
msg11=Adresa webu
msg12=Datum
msg13=Čas
msg14=T
msg15=RH
msg16=Zapnuto
msg17=Vypnuto
msg18=Chyba
msg19=Aktualizováno
msg20=Poslední stav
msg21=Diář
msg22=Kamery
msg23=Pokud chcete zobrazit celý diář, přihlaste se k jednotce pomocí SSH a použijte <i> mm5d-viewlog </i>!
