# +----------------------------------------------------------------------------+
# | MM5D v0.4 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d_ro.msg                                                                |
# | message file                                                               |
# +----------------------------------------------------------------------------+

msg01=MM5D sistem de control
msg02=Date utilizator
msg03=Utilizator
msg04=Numele site-ului
msg05=Cresterea casei
msg06=Nume
msg07=Intrare
msg08=ieșire
msg09=Eroare
msg10=Du-te la date
msg11=Adresa site-ului
msg12=Data
msg13=Timp
msg14=T
msg15=RH
msg16=Pornit
msg17=Oprit
msg18=Eroare
msg19=Actualizat
msg20=Ultima stare
msg21=Jurnal
msg22=Camere
msg23=Dacă doriți să vedeți jurnalul complet, conectați-vă la unitate cu SSH și folosiți <i>mm5d-viewlog</i>!
msg24=Ieșirile de anulare
msg25=neutru
msg26=pornit
msg27=inchis
msg28=Pentru a seta suprascrierea, vă rugăm să vă conectați la unitate prin SSH și să utilizați comanda <i>mm5d-override</i>!
msg29=Pentru a seta caracteristicile mediului, vă rugăm să vă conectați la unitate prin SSH și să utilizați comanda <i>mm5d-editenvirconf</i>!
msg30=Caracteristica mediului
msg31=Hife în creştere
msg32=Cultură de ciuperci
msg33=încălzitor
msg34=umidificator
msg35=ventilator
msg36=lampa
msg37=pornit
msg38=off
msg39=minimum
msg40=maximum
msg41=dezactivați alimentarea
msg42=cronometrat
