#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.6 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2023 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d-prepare                                                               |
# | Prepare OS for install MM5D software                                       |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

line()
{
  for ((i=0; i<${#SWCR}; i++))
  do
    echo -n "-"
  done
  echo ""
}

SWN1="MM5D"
SWN2="mm5d"
SWV="v0.6"
SWCR="Copyright (C) 2019-2023 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>"

# prepare
echo -e "\n$SWN1 v$SWV prepare OS"
echo "$SWCR"
line
echo "Installing required components..."
sudo apt-get install build-essential git python3-dev
echo "Cloning 3rd party softwares from Github..."
mkdir --parents $HOME/download
cd $HOME/download
# clone sensor software
git clone https://github.com/adafruit/Adafruit_Python_DHT.git
cd Adafruit_Python_DHT
sudo python3 setup.py install
cd ..
# clone display software
git clone http://github.com/rm-hull/luma.led_matrix.git
cd luma.led_matrix
sudo python3 setup.py install
echo -e "\nDone."
exit 0

