#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/mm5d-web -a -d /usr/share/doc/mm5d-web ]; then
    ln -sf /usr/share/doc/mm5d-web /usr/doc/mm5d-web
  fi
fi
sudo chown root:www-data /var/www/html/pics
sudo chmod 775 /var/www/html/pics
ln --force --symbolic /etc/apache2/mods-available/cgid.load /etc/apache2/mods-enabled/
ln --force --symbolic /etc/apache2/mods-available/cgid.conf /etc/apache2/mods-enabled/
ln --force --symbolic /etc/apache2/conf-available/serve-cgi-bin.conf /etc/apache2/conf-enabled/
invoke-rc.d apache2 restart
mm5d-updatestartpage
