#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.4 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d-creatediagrams                                                        |
# | Create diagrams for webpage                                                |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: configuration file is missing

loadconfiguration()
{
  #CFGFILE="/etc/mm5d/mm5d.ini"
  CFGFILE="/usr/local/etc/mm5d/mm5d.ini"
  if [ ! -f $CFGFILE ]
    then
      echo "ERROR: Cannot open configuration file!"
      exit 1
  fi
  DIR_HTM=`cat $CFGFILE | grep dir_htm= | sed 's/dir_htm=//'`
  DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
  DIR_TMP=`cat $CFGFILE | grep dir_tmp= | sed 's/dir_tmp=//'`
  WEB_LINES=`cat $CFGFILE | grep web_lines= | sed 's/web_lines=//'`
}

creatediagrams()
{
  TMPFILE=$DIR_HTM"pics/mm5d-creatediagrams.tmp"
  LOGFILE=$DIR_LOG"mm5d.log"
  head -n $WEB_LINES $LOGFILE > $TMPFILE
  gnuplot << EOF
set lmargin at screen 0.10
set rmargin at screen 0.90
set bmargin at screen 0.10
set tmargin at screen 0.90
set datafile separator ","
set title ""
set ylabel ""
set yrange [0:30]
set xlabel ""
unset xtics
set style fill solid 1.00 noborder
set boxwidth 2 relative
set terminal png
set output "$DIR_HTM/pics/temperature.png"
plot "$TMPFILE" using 3:xticlabels(stringcolumn(2)) with lines title "T [degree C]" linecolor rgb 'red'
EOF
  gnuplot << EOF
set lmargin at screen 0.10
set rmargin at screen 0.90
set bmargin at screen 0.10
set tmargin at screen 0.90
set datafile separator ","
set title ""
set ylabel ""
set yrange [0:110]
set xlabel ""
unset xtics
set style fill solid 1.00 noborder
set boxwidth 2 relative
set terminal png
set output "$DIR_HTM/pics/humidity.png"
plot "$TMPFILE" using 4:xticlabels(stringcolumn(2)) with lines title "RH [%]" linecolor rgb 'blue'
EOF
  rm --force $TMPFILE
}

loadconfiguration
creatediagrams
exit 0
