#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM3D v0.4 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2018-2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>      |
# | mm3d-editmainconf                                                          |
# | Edit main configuration file                                               |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

CFGFILE="/usr/local/etc/mm3d/mm3d.ini"
if [ ! -f $CFGFILE ]
then
  echo "ERROR: Cannot open configuration file!"
exit 1
fi

mm3d-stopdaemon
sudo editor $CFGFILE
mm3d-updatestartpage
mm3d-startdaemon
exit 0
