#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.4 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d-editmainconf                                                          |
# | Edit main configuration file                                               |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: configuration file is missing

#CFGFILE="/etc/mm5d/mm5d.ini"
CFGFILE="/usr/local/etc/mm5d/mm5d.ini"
if [ ! -f $CFGFILE ]
then
  echo "ERROR: Cannot open configuration file!"
exit 1
fi

sudo mm5d-editmainconf.bin $CFGFILE
if [ $? -eq 0 ]
then
  mm5d-stopdaemon
  mm5d-updatestartpage
  mm5d-startdaemon
fi
exit 0
