#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.6 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2023 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | mm5d-maintainlog                                                           |
# | Maintain log file                                                          |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: cannot open configuration file
#   4: cannot create backup file

loadconfiguration()
{
  #CFGFILE="/etc/mm5d/mm5d.ini"
  CFGFILE="/usr/local/etc/mm5d/mm5d.ini"
  if [ ! -f $CFGFILE ]
    then
      echo "ERROR: Cannot open configuration file!"
      exit 1
  fi
  LNG=`cat $CFGFILE | grep lng= | sed 's/lng=//'`
  DAY_LOG=`cat $CFGFILE | grep day_log= | sed 's/day_log=//'`
  DIR_LOG=`cat $CFGFILE | grep dir_log= | sed 's/dir_log=//'`
  DIR_LCK=`cat $CFGFILE | grep dir_lck= | sed 's/dir_lck=//'`
  DAY_L=$(($DAY_LOG+1))
}

maintainlogfile()
{
  BCKPFILE="$DIR_LOG/mm5d.bak"
  DATAFILE="$DIR_LOG/mm5d.log"

  rm --force $BCKPFILE.gz
  mv $DATAFILE $BCKPFILE
  touch $DATAFILE
  NOW=`date +%s`
  OLDIFS=$IFS
  IFS=,
  [ ! -f $BCKPFILE ] && { echo "Backup file (mm5d.bak) is not exist!"; exit 2; }
  while read C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12 C13 C14 C15 C16
  do
    XDATE=`date -d $C1 +%s`
    MAXXDATE=$(($XDATE+$((86400*$DAY_L))))
    if ! [ $NOW -gt $MAXXDATE ]
    then
      echo "$C1,$C2,$C3,$C4,$C5,$C6,$C7,$C8,$C9,$C10,$C11,$C12,$C13,$C14,$C15,$C16" >> $DATAFILE
    fi
  done < $BCKPFILE
  IFS=$OLDIFS
  gzip -9 $BCKPFILE
}

# main function
loadconfiguration
maintainlogfile
exit 0
