#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.6 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2023 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | mm5d-editenvirconf                                                         |
# | Edit environment configuration file                                        |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#  14: cannot open environment characteristic configuration file

#CFGFILE="/etc/mm5d/envir.ini"
CFGFILE="/usr/local/etc/mm5d/envir.ini"
if [ ! -f $CFGFILE ]
then
  echo "ERROR: Cannot open environment characteristic configuration file!"
exit 14
fi

sudo mm5d-editenvirconf.bin $CFGFILE
if [ $? -eq 0 ]
then
  mm5d-stopdaemon
  mm5d-startdaemon
fi
exit 0
