#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
# | mm5d-editcurrentprog                                                       |
# | Edit current program file                                                  |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

PRGFILE="/home/mm5d/programs/prg_current.py"
if [ ! -e $PRGFILE ]
then
  echo "ERROR: Cannot open current program file!"
exit 1
fi

editor $PRGFILE
exit 0
