#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.4 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | mm5d-statusofdaemon                                                        |
# | Write status of daemons                                                    |
# +----------------------------------------------------------------------------+

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

/etc/init.d/mm5d.sh status
/etc/init.d/matrixdisplay.sh status
