#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM5D v0.1 * Growing house controlling and remote monitoring system         |
# | Copyright (C) 2019 Pozsár Zsolt <pozsar.zsolt@.szerafingomba.hu>           |
# | mm5d-override                                                              |
# | Override output status                                                     |
# +----------------------------------------------------------------------------+

# Exit codes:
#   0: normal exit
#   1: configuration file is missing
#   2: no or bad command line parameters

#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

loadconfiguration()
{
#  CFGFILE="/usr/local/etc/mm5d/mm5d.ini"
  CFGFILE="./mm5d.ini"
  if [ ! -f $CFGFILE ]
    then
      echo "ERROR: Cannot open configuration file!"
      exit 1
  fi
  DIR_VAR=`cat $CFGFILE | grep dir_var= | sed 's/dir_var=//'`
}

writetofile()
{
  case $1 in
    "heater") OF="out1";;
    "light") OF="out2";;
    "ventilator") OF="out3";;
    "humidifier") OF="out4";;
    *) usage; exit 2;;
  esac
  if [ $2 = "neutral" ] || [ $2 = "on" ] || [ $2 = "off" ]
  then
    #sudo
    echo -n $2 > $DIR_VAR$OF
    echo "Output '"$1"' is set to $2."
    exit 0
  fi
  usage
  exit 2
}

getstatus()
{
  case $1 in
    "heater") IF="out1";;
    "light") IF="out2";;
    "ventilator") IF="out3";;
    "humidifier") IF="out4";;
    *) usage; exit 2;;
  esac
  echo "Port '"$1"' status is:"
  if [ ! -f $DIR_VAR$IF ]
    then
      echo "neutral"
      exit 0
  fi
  cat $DIR_VAR$IF
  echo ""
  exit 0
}

usage()
{
  echo ""
  echo "Usage:"
  echo "    $0 -f|--full-screen"
  echo "    $0 heater|light|ventilator|humidifier neutral|on|off"
  echo ""
}

# main function
loadconfiguration
if [ $# -eq 2 ];
then
  writetofile $1 $2
  exit 0
fi
if [ $# -eq 1 ];
then
  case $1 in
    "-f") mm5d-override.bin $DIR_VAR; exit 0;;
    "--full-screen") mm5d-override.bin $DIR_VAR; exit 0;;
    *) getstatus $1; exit 0;;
  esac
fi
usage
exit 2
