#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/mm3d-prepare -a -d /usr/share/doc/mm3d-prepare ]; then
    ln -sf /usr/share/doc/mm3d-prepare /usr/doc/mm3d-prepare
  fi
fi
echo "Run mm3d-prepare script before install other MM3D packages."
