#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/mm5d-sw -a -d /usr/share/doc/mm5d-sw ]; then
    ln -sf /usr/share/doc/mm5d-sw /usr/doc/mm5d-sw
  fi
fi
mkdir --parents /var/lib/mm5d/
mkfifo /var/tmp/matrixdisplayfifo
invoke-rc.d mm5d.sh stop
invoke-rc.d matrixdisplay.sh stop
ln -sf /etc/init.d/mm5d.sh /etc/rc0.d/K01mm5d.sh
ln -sf /etc/init.d/mm5d.sh /etc/rc2.d/S01mm5d.sh
ln -sf /etc/init.d/mm5d.sh /etc/rc3.d/S01mm5d.sh
ln -sf /etc/init.d/mm5d.sh /etc/rc4.d/S01mm5d.sh
ln -sf /etc/init.d/mm5d.sh /etc/rc5.d/S01mm5d.sh
ln -sf /etc/init.d/mm5d.sh /etc/rc6.d/K01mm5d.sh
ln -sf /etc/init.d/matrixdisplay.sh /etc/rc0.d/K02matrixdisplay.sh
ln -sf /etc/init.d/matrixdisplay.sh /etc/rc2.d/S02matrixdisplay.sh
ln -sf /etc/init.d/matrixdisplay.sh /etc/rc3.d/S02matrixdisplay.sh
ln -sf /etc/init.d/matrixdisplay.sh /etc/rc4.d/S02matrixdisplay.sh
ln -sf /etc/init.d/matrixdisplay.sh /etc/rc5.d/S02matrixdisplay.sh
ln -sf /etc/init.d/matrixdisplay.sh /etc/rc6.d/K02matrixdisplay.sh
systemctl daemon-reload
systemctl enable mm5d.service
systemctl enable matrixdisplay.service
systemctl daemon-reload
invoke-rc.d mm5d.sh start
invoke-rc.d matrixdisplay.sh start
invoke-rc.d cron restart
