#!/bin/sh
set -e
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/mm5d-sw ]; then
  rm -f /usr/doc/mm5d-sw
fi
invoke-rc.d mm5d.sh stop
invoke-rc.d matrixdisplay.sh stop
systemctl enable mm5d.service
systemctl enable matrixdisplay.service
rm -f /var/tmp/matrixdisplayfifo
